baseURL = "https://karso.xyz"
languageCode = 'en-us'
title = "Karso's Meanderings"
disableKinds = ["taxonomy"]
[params]
  author = "Karso Suryo Putro"
  description = """A personal site where I write about things that excite me""" 
  images = ["images/og-default.jpg"]
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      enable = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
