baseURL = "https://karso.xyz"
languageCode = 'en-us'
title = "Karso's Meanderings"
disableKinds = ["taxonomy"]
[params]
  author = "Karso Suryo Putro"
  description = """I'm a normal lad who have interest in science, philosophy,
  and computer tech. I like writing about those as well as other interesting
  things""" 

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      enable = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
